
STARTING_POINT = False
ENDING_POINT = False
WHILE_GAME_POINT = True
WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 750
FLAG_IMAGE = 'flag.png'
SOLDIER_IMAGE = 'soldier.png'
GRASS_IMAGE = 'grass.png'
MINE_IMAGE = 'mine.png'
INJURY_IMAGE = 'injury.png'
SOLDIER_DANGER_IMAGE = 'soldier_nigth.png'
GREEN = (12, 101, 37)
BASIC_GREEN = (0, 180, 0)
BLACK = (0, 0, 0)
MINES_AMOUNT = 20
GRASS_AMOUNT = 20